using System.Collections.Generic;
using UnityEngine;

namespace TripoFaceRig
{
    /// <summary>
    /// Rhythm features extracted from a speech clip: a loudness envelope, the
    /// emphasis beats, and the phrase boundaries.
    ///
    /// Runtime by design. Dialogue here is generated by a local LLM and spoken by
    /// a TTS server, so nothing can be precomputed in Blender - the clip does not
    /// exist until the moment it is needed. Analysis is a single O(samples) pass;
    /// a 20s mono 44.1kHz clip is under a million floats and takes a few ms.
    /// </summary>
    public static class SpeechAnalysis
    {
        public sealed class Result
        {
            /// <summary>Loudness 0..1, one entry per hop.</summary>
            public float[] Envelope;
            public float HopSeconds;
            public float Duration;
            /// <summary>Times (s) of emphasis onsets - where a gesture reads naturally.</summary>
            public List<float> Beats = new List<float>();
            /// <summary>Times (s) where speech resumes after a pause. Safe places to change pose.</summary>
            public List<float> PhraseStarts = new List<float>();

            public float LevelAt(float t)
            {
                if (Envelope == null || Envelope.Length == 0) return 0f;
                int i = Mathf.Clamp(Mathf.FloorToInt(t / HopSeconds), 0, Envelope.Length - 1);
                return Envelope[i];
            }
        }

        /// <param name="hopSeconds">Envelope resolution. 20ms is finer than gesture timing needs.</param>
        /// <param name="silenceLevel">Below this counts as a pause.</param>
        /// <param name="minPause">A gap must last this long to end a phrase.</param>
        /// <param name="minBeatGap">Beats closer together than this are merged; stops twitching.</param>
        public static Result Analyse(AudioClip clip, float hopSeconds = 0.02f,
                                     float silenceLevel = 0.12f, float minPause = 0.22f,
                                     float minBeatGap = 0.45f)
        {
            var r = new Result { HopSeconds = hopSeconds };
            if (clip == null || clip.samples == 0) { r.Envelope = new float[0]; return r; }

            r.Duration = clip.length;
            int channels = Mathf.Max(1, clip.channels);
            var samples = new float[clip.samples * channels];
            if (!clip.GetData(samples, 0))
            {
                // Streaming or compressed-in-memory clips refuse GetData. TTS output
                // is usually decompressed PCM, but say so rather than fail silently.
                Debug.LogWarning($"[TripoFaceRig] Could not read samples from '{clip.name}'. " +
                                 "Set its Load Type to Decompress On Load for gesture analysis.");
                r.Envelope = new float[0];
                return r;
            }

            int hop = Mathf.Max(1, Mathf.RoundToInt(clip.frequency * hopSeconds));
            int frames = clip.samples / hop;
            var env = new float[Mathf.Max(1, frames)];

            for (int f = 0; f < frames; f++)
            {
                double acc = 0;
                int start = f * hop;
                int end = Mathf.Min(clip.samples, start + hop);
                for (int s = start; s < end; s++)
                {
                    float v = samples[s * channels];   // first channel is enough
                    acc += v * v;
                }
                env[f] = Mathf.Sqrt((float)(acc / Mathf.Max(1, end - start)));
            }

            // Normalise against a high percentile so one loud transient does not
            // flatten everything else.
            var sorted = (float[])env.Clone();
            System.Array.Sort(sorted);
            float refLevel = sorted[Mathf.Clamp(Mathf.RoundToInt(0.92f * (sorted.Length - 1)), 0, sorted.Length - 1)];
            if (refLevel <= 1e-6f) refLevel = Mathf.Max(1e-6f, sorted[sorted.Length - 1]);
            for (int i = 0; i < env.Length; i++) env[i] = Mathf.Clamp01(env[i] / refLevel);

            // Light smoothing: gesture timing should follow syllable groups, not phonemes.
            int k = Mathf.Max(1, Mathf.RoundToInt(0.05f / hopSeconds));
            var sm = new float[env.Length];
            for (int i = 0; i < env.Length; i++)
            {
                int a = Mathf.Max(0, i - k), b = Mathf.Min(env.Length, i + k + 1);
                float sum = 0f;
                for (int j = a; j < b; j++) sum += env[j];
                sm[i] = sum / (b - a);
            }
            r.Envelope = sm;

            // Phrase starts: speech resuming after a long enough pause.
            int pauseHops = Mathf.Max(1, Mathf.RoundToInt(minPause / hopSeconds));
            int quiet = pauseHops;      // treat the lead-in as a pause so the first onset counts
            for (int i = 0; i < sm.Length; i++)
            {
                if (sm[i] < silenceLevel) { quiet++; continue; }
                if (quiet >= pauseHops) r.PhraseStarts.Add(i * hopSeconds);
                quiet = 0;
            }

            // Beats: rising edges that clear a margin above the local floor.
            float lastBeat = -999f;
            for (int i = 1; i < sm.Length - 1; i++)
            {
                float t = i * hopSeconds;
                if (t - lastBeat < minBeatGap) continue;
                bool rising = sm[i] > sm[i - 1] && sm[i] >= sm[i + 1];
                if (rising && sm[i] > silenceLevel + 0.25f)
                {
                    r.Beats.Add(t);
                    lastBeat = t;
                }
            }
            return r;
        }
    }
}
