using UnityEngine;

namespace TripoFaceRig
{
    /// <summary>
    /// Makes the body read as "talking" against arbitrary speech, without any
    /// authored sync.
    ///
    /// The premise, which is how most shipped dialogue works: viewers read
    /// lipsync tightly and body gesture loosely. The face is already frame
    /// accurate, so the body only has to be PLAUSIBLE - move when she speaks,
    /// emphasise roughly where she emphasises, settle when she stops. Matching
    /// specific words is a hand-authoring job and is not attempted here.
    ///
    /// Built runtime-first because dialogue is generated by a local LLM and
    /// spoken by a TTS server: the clip does not exist ahead of time, so nothing
    /// can be baked. Call Speak(clip) when the TTS audio arrives.
    ///
    /// Animator contract:
    ///   Speaking     bool   true while audio plays
    ///   SpeechLevel  float  0..1 smoothed loudness - drive a blend tree with it
    ///   Gesture      trigger fired on emphasis beats
    ///   GestureIndex int    which gesture to play, set just before the trigger
    /// </summary>
    [DefaultExecutionOrder(-100)]
    [RequireComponent(typeof(AudioSource))]
    public sealed class SpeechGestureDriver : MonoBehaviour
    {
        [SerializeField] private Animator animator;
        [SerializeField] private AudioSource audioSource;

        [Header("Animator parameters")]
        [SerializeField] private string speakingParam = "Speaking";
        [SerializeField] private string levelParam = "SpeechLevel";
        [SerializeField] private string gestureTrigger = "Gesture";
        [SerializeField] private string gestureIndexParam = "GestureIndex";
        [SerializeField] private int gestureCount = 3;

        [Header("Feel")]
        [Tooltip("Seconds for SpeechLevel to follow the envelope. Too fast reads as twitchy.")]
        [SerializeField] private float levelSmoothing = 0.12f;
        [Tooltip("Minimum seconds between gestures, on top of the analyser's own spacing.")]
        [SerializeField] private float minGestureInterval = 1.4f;
        [Tooltip("Only gesture on beats at or above this loudness. Raise for a calmer character.")]
        [SerializeField] private float gestureThreshold = 0.55f;
        [Tooltip("Prefer starting a gesture at a phrase start rather than mid-word.")]
        [SerializeField] private bool preferPhraseStarts = true;
        [SerializeField] private float phraseWindow = 0.20f;

        [Header("Testing")]
        [Tooltip("Clip to speak on Start, for testing without the TTS system. " +
                 "Leave empty in production - dialogue arrives via Speak().")]
        [SerializeField] private AudioClip testClip;
        [SerializeField] private bool speakOnStart = false;

        [SerializeField] private bool diagnose = false;

        [Header("Coordinated performance")]
        [SerializeField] private SpeechPerformanceProfile performanceProfile;
        [SerializeField] private int performanceLayer = 1;

        private struct ScheduledGesture
        {
            public int segment;
            public float accent, strength;
        }

        private readonly System.Collections.Generic.List<ScheduledGesture> performance =
            new System.Collections.Generic.List<ScheduledGesture>();
        private AudioClip analysedClip;
        private float performanceTime, previousAudioTime;
        private int activePerformance = -1;
        private bool performancePlaying;
        private readonly System.Collections.Generic.HashSet<int> parameterIds =
            new System.Collections.Generic.HashSet<int>();
        private RuntimeAnimatorController cachedController;

        public SpeechPerformanceProfile PerformanceProfile => performanceProfile;
        public SpeechAnalysis.Result Analysis => analysis;
        public AudioClip AnalysedClip => analysedClip;
        public bool UsesPerformanceProfile => performanceProfile != null &&
            animator != null && performanceLayer >= 0 && performanceLayer < animator.layerCount &&
            Has("GestureTime", AnimatorControllerParameterType.Float);
        public float PerformanceTime => performanceTime;
        public int LineSerial { get; private set; }
        public int PhraseIndex { get; private set; } = -1;
        public float PauseSeconds { get; private set; }
        public float GestureEnvelope { get; private set; }
        public float AccentPulse { get; private set; }
        public float NodPulse { get; private set; }
        public int ScheduledGestureCount => performance.Count;
        public int ActiveGestureSequence => activePerformance;

        private SpeechAnalysis.Result analysis;
        private int nextBeat;
        private float lastGestureTime = -999f;
        private float level;
        private int lastGestureIndex = -1;

        /// <summary>Smoothed 0..1 speech loudness. Other face drivers read this.</summary>
        public float Level => level;

        /// <summary>True while a clip is being analysed and played.</summary>
        public bool IsSpeaking => analysis != null && audioSource != null && audioSource.isPlaying;

        private void Reset()
        {
            animator = GetComponentInChildren<Animator>();
            audioSource = GetComponent<AudioSource>();
        }

        private void Awake()
        {
            if (animator == null) animator = GetComponentInChildren<Animator>();
            if (audioSource == null) audioSource = GetComponent<AudioSource>();
        }

        private System.Collections.IEnumerator Start()
        {
            if (!speakOnStart || testClip == null) yield break;
            // Let the scene settle first. uLipSync follows live audio so it does
            // not care, but the gesture beats are indexed off audioSource.time.
            int calm = 0; float waited = 0f;
            while (calm < 3 && waited < 5f)
            {
                yield return null;
                waited += Time.unscaledDeltaTime;
                calm = Time.unscaledDeltaTime < 0.05f ? calm + 1 : 0;
            }
            Speak(testClip);
        }

        /// <summary>Analyse and speak a clip that arrived at runtime from TTS.</summary>
        public void Speak(AudioClip clip)
        {
            if (clip == null) return;
            if (audioSource == null) audioSource = GetComponent<AudioSource>();
            analysis = SpeechAnalysis.Analyse(clip);
            nextBeat = 0;
            lastGestureTime = -999f;
            BeginPerformance(clip);

            audioSource.clip = clip;
            audioSource.Stop();
            audioSource.time = 0f;
            audioSource.Play();

            lastGestureIndex = Random.Range(0, Mathf.Max(1, gestureCount));
            SetInt(gestureIndexParam, lastGestureIndex);
            SetBool(speakingParam, true);
            if (diagnose)
                Debug.Log($"[TripoFaceRig] Speak '{clip.name}' {clip.length:0.00}s: " +
                          $"{analysis.Beats.Count} beats, {analysis.PhraseStarts.Count} phrases.", this);
        }

        /// <summary>Drive gestures for a clip an AudioSource is already playing.</summary>
        public void DriveExisting()
        {
            if (audioSource == null || audioSource.clip == null) return;
            analysis = SpeechAnalysis.Analyse(audioSource.clip);
            nextBeat = 0;
            lastGestureTime = -999f;
            BeginPerformance(audioSource.clip);
            lastGestureIndex = Random.Range(0, Mathf.Max(1, gestureCount));
            SetInt(gestureIndexParam, lastGestureIndex);
            SetBool(speakingParam, true);
            if (diagnose)
                Debug.Log($"[TripoFaceRig] Driving existing '{audioSource.clip.name}': " +
                          $"{analysis.Beats.Count} beats, {analysis.PhraseStarts.Count} phrases.", this);
        }

        public void StopSpeaking()
        {
            if (audioSource != null) audioSource.Stop();
            SetBool(speakingParam, false);
            SetFloat(levelParam, 0f);
            level = 0f;
            analysis = null;
            performancePlaying = false;
            GestureEnvelope = AccentPulse = NodPulse = 0f;
            activePerformance = -1;
            ResetGestureTrigger();
        }

        private void Update()
        {
            if (audioSource == null) return;

            if (UsesPerformanceProfile)
            {
                UpdatePerformance();
                return;
            }

            // If something else started a clip (FacePerformancePlayer owns the baked
            // take), pick it up rather than requiring an explicit call.
            if (analysis == null && audioSource.isPlaying && audioSource.clip != null)
                DriveExisting();

            if (analysis == null) return;

            if (!audioSource.isPlaying)
            {
                if (level > 0.001f || GetBoolSafe(speakingParam)) StopSpeaking();
                return;
            }

            float t = audioSource.time;

            // Smoothed loudness, for a blend tree between calm and animated talking.
            float target = analysis.LevelAt(t);
            level = Mathf.Lerp(level, target, 1f - Mathf.Exp(-Time.deltaTime / Mathf.Max(0.01f, levelSmoothing)));
            SetFloat(levelParam, level);

            // Advance past beats already gone by (a hitch can skip several).
            while (nextBeat < analysis.Beats.Count && analysis.Beats[nextBeat] < t - 0.15f)
                nextBeat++;

            if (nextBeat >= analysis.Beats.Count) return;
            float beat = analysis.Beats[nextBeat];
            if (t < beat) return;

            nextBeat++;
            if (t - lastGestureTime < minGestureInterval) return;
            if (analysis.LevelAt(beat) < gestureThreshold) return;
            if (preferPhraseStarts && !NearPhraseStart(beat)) return;

            lastGestureTime = t;
            // Must differ from the loop already playing. If it repeated, no
            // transition would match, and Unity would leave the trigger SET to be
            // consumed at some arbitrary later moment.
            int idx = PickDifferent();
            if (idx < 0) return;
            lastGestureIndex = idx;
            SetInt(gestureIndexParam, idx);
            SetTrigger(gestureTrigger);
            if (diagnose) Debug.Log($"[TripoFaceRig] gesture at {t:0.00}s", this);
        }

        private void BeginPerformance(AudioClip clip)
        {
            analysedClip = clip;
            performanceTime = previousAudioTime = PauseSeconds = 0f;
            PhraseIndex = activePerformance = -1;
            GestureEnvelope = AccentPulse = NodPulse = 0f;
            performancePlaying = true;
            LineSerial++;
            ResetGestureTrigger();
            performance.Clear();
            if (!UsesPerformanceProfile) return;

            if (clip == performanceProfile.referenceClip && performanceProfile.referenceGestures.Length > 0)
            {
                foreach (var cue in performanceProfile.referenceGestures)
                    AddPerformance(cue.segment, cue.accentTime, cue.strength);
            }
            else
            {
                int segment = 0;
                float last = -99f;
                foreach (float beat in analysis.Beats)
                {
                    if (beat < 0.65f || beat - last < performanceProfile.minimumGestureGap ||
                        analysis.LevelAt(beat) < gestureThreshold) continue;
                    if (performanceProfile.gestures.Length == 0) break;
                    int before = performance.Count;
                    AddPerformance(segment++ % performanceProfile.gestures.Length, beat,
                        Mathf.Lerp(0.65f, 1f, analysis.LevelAt(beat)));
                    if (performance.Count > before) last = beat;
                }
            }
            if (diagnose) Debug.Log($"[TripoFaceRig] Planned {performance.Count} gesture accents for '{clip.name}'.", this);
        }

        private void AddPerformance(int index, float accent, float strength)
        {
            if (index < 0 || index >= performanceProfile.gestures.Length || !float.IsFinite(accent)) return;
            var segment = performanceProfile.gestures[index];
            if (!segment.IsValid || !animator.HasState(performanceLayer, Animator.StringToHash(segment.stateName))) return;
            float start = accent - (segment.accent - segment.start);
            if (start < 0f || accent >= analysedClip.length) return;
            if (performance.Count > 0)
            {
                var previous = performance[performance.Count - 1];
                var previousSegment = performanceProfile.gestures[previous.segment];
                float previousEnd = previous.accent + previousSegment.end - previousSegment.accent;
                if (start < previousEnd + 0.12f) return;
            }
            performance.Add(new ScheduledGesture { segment = index, accent = accent, strength = Mathf.Clamp01(strength) });
        }

        private void UpdatePerformance()
        {
            if (audioSource.isPlaying && audioSource.clip != null &&
                (analysis == null || analysedClip != audioSource.clip ||
                 audioSource.time + 0.1f < previousAudioTime || !performancePlaying))
                DriveExisting();

            bool playing = audioSource.isPlaying && analysis != null;
            if (playing)
            {
                performanceTime = audioSource.timeSamples / (float)audioSource.clip.frequency;
                previousAudioTime = performanceTime;
                float targetLevel = analysis.LevelAt(performanceTime);
                level = Mathf.Lerp(level, targetLevel, 1f - Mathf.Exp(-Time.unscaledDeltaTime / Mathf.Max(0.01f, levelSmoothing)));
                PauseSeconds = targetLevel < 0.12f ? PauseSeconds + Time.unscaledDeltaTime : 0f;
                while (PhraseIndex + 1 < analysis.PhraseStarts.Count &&
                       analysis.PhraseStarts[PhraseIndex + 1] <= performanceTime) PhraseIndex++;
            }
            else
            {
                performancePlaying = false;
                performanceTime += Time.unscaledDeltaTime;
                level = Mathf.MoveTowards(level, 0f, Time.unscaledDeltaTime * 3f);
                PauseSeconds += Time.unscaledDeltaTime;
            }
            SetBool(speakingParam, playing);
            SetFloat(levelParam, level);
            GestureEnvelope = AccentPulse = NodPulse = 0f;

            for (int i = 0; i < performance.Count; i++)
            {
                var cue = performance[i];
                var segment = performanceProfile.gestures[cue.segment];
                float sourceTime = segment.accent + performanceTime - cue.accent;
                // After an interruption only an already-started gesture may recover.
                if (!playing && i != activePerformance) continue;
                if (sourceTime < segment.start || sourceTime > segment.end) continue;
                if (activePerformance != i)
                {
                    activePerformance = i;
                    animator.Play(Animator.StringToHash(segment.stateName), performanceLayer, 0f);
                    SetInt(gestureIndexParam, cue.segment);
                }
                SetFloat("GestureTime", Mathf.Clamp01(sourceTime / segment.clip.length));
                GestureEnvelope = segment.WeightAt(sourceTime) * cue.strength;
                float distance = (performanceTime - cue.accent) / 0.17f;
                AccentPulse = Mathf.Exp(-distance * distance) * cue.strength;
                NodPulse = i % 2 == 0 ? AccentPulse : 0f;
                break;
            }
        }

        private void ResetGestureTrigger()
        {
            if (Has(gestureTrigger, AnimatorControllerParameterType.Trigger)) animator.ResetTrigger(gestureTrigger);
        }

        private void OnDisable()
        {
            GestureEnvelope = AccentPulse = NodPulse = 0f;
            if (animator != null && performanceLayer >= 0 && performanceLayer < animator.layerCount && performanceProfile != null)
                animator.SetLayerWeight(performanceLayer, 0f);
            ResetGestureTrigger();
        }

        private int PickDifferent()
        {
            if (gestureCount <= 1) return -1;
            int idx = Random.Range(0, gestureCount);
            if (idx == lastGestureIndex) idx = (idx + 1 + Random.Range(0, gestureCount - 1)) % gestureCount;
            return idx;
        }

        private bool NearPhraseStart(float t)
        {
            var ps = analysis.PhraseStarts;
            for (int i = 0; i < ps.Count; i++)
                if (Mathf.Abs(ps[i] - t) <= phraseWindow) return true;
            return false;
        }

        // Animator throws if a parameter is missing, and this component is meant to
        // be droppable onto controllers that only implement part of the contract.
        private bool Has(string name, AnimatorControllerParameterType type)
        {
            if (animator == null || string.IsNullOrEmpty(name) || animator.runtimeAnimatorController == null)
                return false;
            if (cachedController != animator.runtimeAnimatorController)
            {
                cachedController = animator.runtimeAnimatorController;
                parameterIds.Clear();
                foreach (var p in animator.parameters) parameterIds.Add(p.nameHash ^ ((int)p.type << 24));
            }
            return parameterIds.Contains(Animator.StringToHash(name) ^ ((int)type << 24));
        }

        private void SetBool(string n, bool v) { if (Has(n, AnimatorControllerParameterType.Bool)) animator.SetBool(n, v); }
        private void SetFloat(string n, float v) { if (Has(n, AnimatorControllerParameterType.Float)) animator.SetFloat(n, v); }
        private void SetInt(string n, int v) { if (Has(n, AnimatorControllerParameterType.Int)) animator.SetInteger(n, v); }
        private void SetTrigger(string n) { if (Has(n, AnimatorControllerParameterType.Trigger)) animator.SetTrigger(n); }
        private bool GetBoolSafe(string n) => Has(n, AnimatorControllerParameterType.Bool) && animator.GetBool(n);
    }
}
